workflows:
  ios-unsigned:
    name: iOS Unsigned IPA

    environment:
      flutter: 3.41.0
      xcode: latest

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build unsigned archive
        script: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r Runner.ipa Payload

    artifacts:
      - Runner.ipa
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
