workflows:
  ios-unsigned:
    name: iOS Unsigned IPA

    environment:
      flutter: 3.41.0
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get packages
        script: |
          flutter pub get

      - name: Build unsigned IPA
        script: |
          flutter build ipa \
            --release \
            --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - phong2k4zero@email.com
